### ISSUE TITLE
Suggestion: Add option to name a map

### ISSUE THREAD

**Issue by yukidaruma** [tryashtar/image-map#33]
It would be very useful if I can name a map like you can do with cartography table.

Also, this isn't a big deal but I personally think it makes more sense if the map generated has locked state.

Edit: About locked state, it's not supported only on Bedrock Edition.

Edit 2: Can I make a pull request about locked state for BE?

**Comment by tryashtar** [comment]
Hmm I don't think it would really work to make them nameable, since that's a part of the item itself rather than the abstract "map" (names wouldn't transfer from world->program and vice versa). Might be easier to just name them in an anvil in-game.

As for the Bedrock locked mode, yep thanks for the PR. I'll merge it in as soon as I can test it myself

**Comment by yukidaruma** [comment]
I see. That makes sense. Please feel free to close this issue.
