### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Ohanie** [tryashtar/image-map#68]
Does this work on Realms ?

**Comment by tryashtar** [comment]
I can't test specifically, but I see no reason why not. Of course, you'd have to download the realm, add the maps, then upload it again

**Comment by ejm554** [comment]
> 
> 
> I can't test specifically, but I see no reason why not. Of course, you'd have to download the realm, add the maps, then upload it again

I had the same question as the OP, and I was worried that this was going to be the answer. Our world is ~500MB, so uploading is a pain. **Is it possible to do it another way, such as by way of add-ons?**

**Comment by tryashtar** [comment]
Well, let's see. We just need to create a map file with the proper colors. The fastest way is just to generate the file; that's what this program does. But when your access to the files is limited to what you can do in-game, that's not an option.

Of course, it's possible to create map images in-game simply by building blocks, such as with the help of this tool:
https://www.reddit.com/r/Minecraft/comments/gu1npm/i_updated_my_tool_to_help_you_create_map_art_in/

If you want to just build the blocks manually in survival/creative, that's an option. You could also place the blocks with commands, but I am not aware of any tool that can convert a structure file to commands. It would have to be in one-click form since you also wouldn't have access to functions
